[package]
name = "cmtest"
version = "0.1.0"
edition = "2021"

[dependencies]
cxx = { version = "1.0.136", features = ["c++14"] }

[build-dependencies]
cxx-build = "1.0.136"
cmake = "0.1.52"
ar = "0.9.0"
walkdir = "2.5.0"
regex = "1.11.1"
object = "0.36.7"
solvent = "0.8.3"
